service: test

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packagePath: ./package.json

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 350
  stage: ${opt:stage, 'dev'}
  region: eu-west-3
  environment:
    AIRTABLE_BASE_ID: ${env:AIRTABLE_BASE_ID}
    AIRTABLE_API_KEY: ${env:AIRTABLE_API_KEY}
    AIRTABLE_TABLE: ${env:AIRTABLE_TABLE}

plugins:
  - serverless-webpack

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  f1:
    name: ${self:provider.stage}-f1
    description: Test
    handler: handler.f1
    events:
      - http:
          path: f1
          method: get